### ISSUE TITLE
请教一下运行问题

### ISSUE THREAD

**Issue by junwenZhang** [wangxianliang/shufflenet_v2_tensorflow#1]
使用shufflenet v2的网络训练的时候，提示错误，这一句是不是有问题呢?
shortcut, residual = tf.split(inputs, [depth_left, depth], axis=-1)

前面打印出来的值是：
inputs  Tensor("shufflenet_v2/block1/unit_1/shufflenetv2/channel_shuffle/Reshape_1:0", shape=(?, 6, 6, 232), dtype=float32)
depth  116 left_ratio  0.5
depth_left  58
depth  58

Traceback (most recent call last):
  File "train.py", line 410, in <module>
    tf.app.run(main)
  File "/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 97, in main
    train()
  File "train.py", line 137, in train
    gesture_model.build_model()
  File "/Users/xuanxia/Documents/YunOS/machinelearning/driver/data/selfcapture/tf_train/train/model/gesture_recognition_model.py", line 77, in build_model
    num_classes=self.model_params.num_classes)
  File "/Users/xuanxia/Documents/YunOS/machinelearning/driver/data/selfcapture/tf_train/train/model/shufflenet_v2.py", line 207, in shufflenet_v2
    scope=scope)
  File "/Users/xuanxia/Documents/YunOS/machinelearning/driver/data/selfcapture/tf_train/train/model/shufflenet_v2.py", line 147, in shufflenet_v2_base
    net = stack_blocks_dense(net, blocks, output_stride)
  File "/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/Users/xuanxia/Documents/YunOS/machinelearning/driver/data/selfcapture/tf_train/train/model/shufflenet.py", line 175, in stack_blocks_dense
    net = block.unit_fn(net, rate=1, **unit)
  File "/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/Users/xuanxia/Documents/YunOS/machinelearning/driver/data/selfcapture/tf_train/train/model/shufflenet_v2.py", line 48, in shufflenet_v2_unit
    shortcut, residual = tf.split(inputs, [depth_left, depth], axis=-1)
  File "/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1277, in split
    name=name)
  File "/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5137, in _split_v
    num_split=num_split, name=name)
  File "/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)

ValueError: Sum of output sizes must match the size of the original Tensor along the split dimension or the sum of the positive sizes must be less if it contains a -1 for 'shufflenet_v2/block1/unit_2/shufflenetv2/split' (op: 'SplitV') with input shapes: [?,6,6,232], [2], [] and with computed input tensors: input[1] = <58 58>, input[2] = <-1>.

**Comment by Alxemade** [comment]
我也遇到了同样的问题，请问作者解决了吗
